yii2-app-basic/controllers/MetadataDashboardController.php
<?php

/* 
 * @package integrate codebase-with-database v0.0.0.4 (To insert all mvc code files names and paths into the database so the code files can be managed more efficiently and effectively)
 * @package database driven bulk find-replace v0.0.0.3 (To Mass manipulate the code by rule-sets stored in the database)
 * @package cec tracking v0.0.0.0      (to know the code by its adherence to certain design principles)
 * @package package tracking v0.0.0.0  (to know the code by its call stacks eg it's actionable trees of code)
 * @package automated system tests v0.0.0.0  (to validate the code base and specifically codebase-to-database interactions)
 */

/**
 * CEC - Consistent Engineering Criteria
 * cec-y1c-0001-code-layout-00 - A controller is a collection of packages. 
 * Each package has an inherent code maturity and code attrition level. 
 * A package is a code implementation of a desired feature.
 * ? List features implemented by the controller file?
 * ? List the packages of the controller
 * ? List the packages by feature
 * ? I want to see the code base by features, packages, and action trees eg code-coverage and call stacks
 * My purpose : to bring divine clarity, structure, and understanding to the code base and application.
 */

namespace app\controllers;

use Yii;
use app\models\MetadataCodebase;
use app\models\MetadataCodebaseSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\base\UserException;

//use \app\modules\dbyrd\functions;

/**
 * MetadataCodebaseController implements the CRUD actions for MetadataCodebase model.
 * @since 0.7.0
 */
class MetadataDashboardController extends Controller
{
    public $layout = 'column1-menu-metadata';
    //public $defaultAction = 'admin';
    protected $appPath = '';
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    
    /**
     * Lists all MetadataCodebase models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MetadataCodebaseSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        //$this->layout='column1-menu.php'; // this works
        //$this->getDatabaseSchema3Stats([]);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MetadataCodebase model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $providerMetadataCodebaseCecStatus = new \yii\data\ArrayDataProvider([
            'allModels' => $model->metadataCodebaseCecStatuses,
        ]);
        $providerMetadataCodebaseControl = new \yii\data\ArrayDataProvider([
            'allModels' => $model->metadataCodebaseControls,
        ]);
        $providerMetadataCodebaseView = new \yii\data\ArrayDataProvider([
            'allModels' => $model->metadataCodebaseViews,
        ]);
        $this->layout='//layouts/column1-menu.php';
        return $this->render('view', [
            'model' => $this->findModel($id),
            'providerMetadataCodebaseCecStatus' => $providerMetadataCodebaseCecStatus,
            'providerMetadataCodebaseControl' => $providerMetadataCodebaseControl,
            'providerMetadataCodebaseView' => $providerMetadataCodebaseView,
        ]);
    }

    /**
     * Creates a new MetadataCodebase model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MetadataCodebase();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->codebase_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing MetadataCodebase model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (Yii::$app->request->post('_asnew') == '1') {
            $model = new MetadataCodebase();
        }else{
            $model = $this->findModel($id);
        }

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->codebase_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing MetadataCodebase model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->deleteWithRelated();

        return $this->redirect(['index']);
    }

    /**
    * Creates a new MetadataCodebase model by another data,
    * so user don't need to input all field from scratch.
    * If creation is successful, the browser will be redirected to the 'view' page.
    *
    * @param mixed $id
    * @return mixed
    */
    public function actionSaveAsNew($id) {
        $model = new MetadataCodebase();

        if (Yii::$app->request->post('_asnew') != '1') {
            $model = $this->findModel($id);
        }
    
        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            return $this->redirect(['view', 'id' => $model->codebase_id]);
        } else {
            return $this->render('saveAsNew', [
                'model' => $model,
            ]);
        }
    }
    
    /**
     * Finds the MetadataCodebase model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MetadataCodebase the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MetadataCodebase::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
    * Action to load a tabular form grid
    * for MetadataCodebaseCecStatus
    * @author Yohanes Candrajaya <moo.tensai@gmail.com>
    * @author Jiwantoro Ndaru <jiwanndaru@gmail.com>
    *
    * @return mixed
    */
    public function actionAddMetadataCodebaseCecStatus()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('MetadataCodebaseCecStatus');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('_action') == 'load' && empty($row)) || Yii::$app->request->post('_action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formMetadataCodebaseCecStatus', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
    * Action to load a tabular form grid
    * for MetadataCodebaseControl
    * @author Yohanes Candrajaya <moo.tensai@gmail.com>
    * @author Jiwantoro Ndaru <jiwanndaru@gmail.com>
    *
    * @return mixed
    */
    public function actionAddMetadataCodebaseControl()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('MetadataCodebaseControl');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('_action') == 'load' && empty($row)) || Yii::$app->request->post('_action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formMetadataCodebaseControl', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
    * Action to load a tabular form grid
    * for MetadataCodebaseView
    * @author Yohanes Candrajaya <moo.tensai@gmail.com>
    * @author Jiwantoro Ndaru <jiwanndaru@gmail.com>
    *
    * @return mixed
    */
    public function actionAddMetadataCodebaseView()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('MetadataCodebaseView');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('_action') == 'load' && empty($row)) || Yii::$app->request->post('_action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formMetadataCodebaseView', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    protected function getFilesFromDisk($params) {
        // by file function?
        $codeFunctions = \app\models\MetadataCodebaseFunction::find()->all();
        
        
    }
    
    
    
// mature code
    
    // <editor-fold defaultstate="collapsed" desc="package integrate codebase-with-database v0.0.0.4">
    // * package name: integrate codebase-with-database v0.0.0.4 
    // * package purpose: To insert all mvc code files names and paths into the 
    // database so the code files can be managed more efficiently and effectively.

    
    /**
     * Load code base table with entries
     * @package bulk find-replace v1
     */
    public function actionPopulate()
    {
        $basePath = Yii::getAlias('@app'); // .../yii2-app-basic
        $codeFolders = [
            'models'         => $basePath . '/models',
            'models/base'    => $basePath . '/models/base',
            'controllers'    => $basePath . '/controllers',
            'views'          => $basePath . '/views',
            ];

yii2-app-basic/views/metadata-dashboard/_dataMetadataCodebaseCecStatus.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->metadataCodebaseCecStatuses,
        'key' => 'cec_status_id'
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        'cec_status_id',
        [
                'attribute' => 'codebaseCec.codebase_cec_id',
                'value' => 'codebaseCec.codebase_cec',
                'label' => 'CEC Codebase'
            ],
        'cec_status',
        'cec_status_tag',
        'cec_status_bfr',
        'cec_status_at',
        ['attribute' => 'lock', 'visible' => false],
        [
            'class' => 'yii\grid\ActionColumn',
            'controller' => 'metadata-codebase-cec-status'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

yii2-app-basic/views/metadata-dashboard/_dataMetadataCodebaseDevStatus.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->metadataCodebaseDevStatuses,
        'key' => 'dev_status_id'
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        'dev_status_id',
        [
                'attribute' => 'codebaseDev.codebase_dev_id',
                'label' => 'Codebase Dev'
            ],
        'dev_status',
        'dev_status_tag',
        'dev_status_bfr',
        'dev_status_at',
        ['attribute' => 'lock', 'visible' => false],
        [
            'class' => 'yii\grid\ActionColumn',
            'controller' => 'metadata-codebase-dev-status'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

yii2-app-basic/views/metadata-dashboard/_dataMetadataCodebaseMvcControl.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->metadataCodebaseMvcControls,
        'key' => 'codebase_mvc_control_id'
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        'codebase_mvc_control_id',
        'controller_actions',
        'action_function',
        'action_params',
        'action_url:url',
        ['attribute' => 'lock', 'visible' => false],
        [
            'class' => 'yii\grid\ActionColumn',
            'controller' => 'metadata-codebase-mvc-control'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

yii2-app-basic/views/metadata-dashboard/_dataMetadataCodebaseMvcView.php
<?php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

    $dataProvider = new ArrayDataProvider([
        'allModels' => $model->metadataCodebaseMvcViews,
        'key' => 'codebase_mvc_view_id'
    ]);
    $gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        'codebase_mvc_view_id',
        'view_function',
        'view_file',
        'view_params',
        'view_url:url',
        ['attribute' => 'lock', 'visible' => false],
        [
            'class' => 'yii\grid\ActionColumn',
            'controller' => 'metadata-codebase-mvc-view'
        ],
    ];
    
    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'containerOptions' => ['style' => 'overflow: auto'],
        'pjax' => true,
        'beforeHeader' => [
            [
                'options' => ['class' => 'skip-export']
            ]
        ],
        'export' => [
            'fontAwesome' => true
        ],
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'showPageSummary' => false,
        'persistResize' => false,
    ]);

yii2-app-basic/views/metadata-dashboard/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\MetadataCodebase */
/* @var $form yii\widgets\ActiveForm */

\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MetadataCodebaseCecStatus', 
        'relID' => 'metadata-codebase-cec-status', 
        'value' => \yii\helpers\Json::encode($model->metadataCodebaseCecStatuses),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MetadataCodebaseDevStatus', 
        'relID' => 'metadata-codebase-dev-status', 
        'value' => \yii\helpers\Json::encode($model->metadataCodebaseDevStatuses),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MetadataCodebaseMvcControl', 
        'relID' => 'metadata-codebase-mvc-control', 
        'value' => \yii\helpers\Json::encode($model->metadataCodebaseMvcControls),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MetadataCodebaseMvcModel', 
        'relID' => 'metadata-codebase-mvc-model', 
        'value' => \yii\helpers\Json::encode($model->metadataCodebaseMvcModels),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
\mootensai\components\JsBlock::widget(['viewFile' => '_script', 'pos'=> \yii\web\View::POS_END, 
    'viewParams' => [
        'class' => 'MetadataCodebaseMvcView', 
        'relID' => 'metadata-codebase-mvc-view', 
        'value' => \yii\helpers\Json::encode($model->metadataCodebaseMvcViews),
        'isNewRecord' => ($model->isNewRecord) ? 1 : 0
    ]
]);
?>

<div class="metadata-codebase-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'codebase_id')->textInput(['placeholder' => 'Codebase']) ?>

    <?= $form->field($model, 'file_name')->textInput(['maxlength' => true, 'placeholder' => 'File Name']) ?>

    <?= $form->field($model, 'file_path_uri')->textInput(['maxlength' => true, 'placeholder' => 'File Path Uri']) ?>

    <?= $form->field($model, 'lock', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?php
    $forms = [
        [
            'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('CEC Status'),
            'content' => $this->render('_formMetadataCodebaseCecStatus', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->metadataCodebaseCecStatuses),
            ]),
        ],
        [
            'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('Development Status'),
            'content' => $this->render('_formMetadataCodebaseDevStatus', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->metadataCodebaseDevStatuses),
            ]),
        ],
        [
            'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('MVC Controllers'),
            'content' => $this->render('_formMetadataCodebaseMvcControl', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->metadataCodebaseMvcControls),
            ]),
        ],
        [
            'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('MVC Models'),
            'content' => $this->render('_formMetadataCodebaseMvcModel', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->metadataCodebaseMvcModels),
            ]),
        ],
        [
            'label' => '<i class="glyphicon glyphicon-book"></i> ' . Html::encode('MVC Views'),
            'content' => $this->render('_formMetadataCodebaseMvcView', [
                'row' => \yii\helpers\ArrayHelper::toArray($model->metadataCodebaseMvcViews),
            ]),
        ],
    ];
    echo kartik\tabs\TabsX::widget([
        'items' => $forms,
        'position' => kartik\tabs\TabsX::POS_ABOVE,
        'encodeLabels' => false,
        'pluginOptions' => [
            'bordered' => true,
            'sideways' => true,
            'enableCache' => false,
        ],
    ]);
    ?>
    <div class="form-group">
    <?php if(Yii::$app->controller->action->id != 'save-as-new'): ?>
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    <?php endif; ?>
    <?php if(Yii::$app->controller->action->id != 'create'): ?>
        <?= Html::submitButton('Save As New', ['class' => 'btn btn-info', 'value' => '1', 'name' => '_asnew']) ?>
    <?php endif; ?>
        <?= Html::a(Yii::t('app', 'Cancel'), Yii::$app->request->referrer , ['class'=> 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

yii2-app-basic/views/metadata-dashboard/_formMetadataCodebaseControl.php
<div class="form-group" id="add-metadata-codebase-control">
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;

$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'MetadataCodebaseControl',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        'codebase_control_id' => ['type' => TabularForm::INPUT_HIDDEN],
        'controller_actions' => ['type' => TabularForm::INPUT_TEXT],
        'action_function' => ['type' => TabularForm::INPUT_TEXT],
        'action_params' => ['type' => TabularForm::INPUT_TEXT],
        'action_url' => ['type' => TabularForm::INPUT_TEXT],
        "lock" => ['type' => TabularForm::INPUT_HIDDEN, 'columnOptions' => ['hidden'=>true]],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return
                    Html::hiddenInput('Children[' . $key . '][id]', (!empty($model['id'])) ? $model['id'] : "") .
                    Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  'Delete', 'onClick' => 'delRowMetadataCodebaseControl(' . $key . '); return false;', 'id' => 'metadata-codebase-control-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => false,
            'type' => GridView::TYPE_DEFAULT,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="glyphicon glyphicon-plus"></i>' . 'Add Metadata  Codebase Control', ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowMetadataCodebaseControl()']),
        ]
    ]
]);
echo  "    </div>\n\n";
?>

yii2-app-basic/views/metadata-dashboard/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: '_action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

yii2-app-basic/views/metadata-dashboard/indexOfTables.php
<?php

/* @var $this yii\web\View */
/* @var $searchModel app\models\MetadataCodebaseSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use yii\helpers\Html;
//use kartik\export\ExportMenu;
use kartik\grid\GridView;
//use yii\grid\GridView;


$this->title = 'Codebase Metadata';
$this->params['breadcrumbs'][] = ['label'=>'Metadata','url'=>'/metadata-dashboard/index'];
$this->params['breadcrumbs'][] = ['label'=>'Codebase','url'=>'/metadata-dashboard/index'];
//$this->params['breadcrumbs'][] = $this->title;
$search = "$('.search-button').click(function(){
	$('.search-form').toggle(1000);
	return false;
});";
//$this->registerJs($search);
?>
<div class="metadata-codebase-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Codebase Metadata', ['populate'], ['class' => 'btn btn-success']) ?>

    </p>
    <?php 
//    $customer_persons_data = (new \yii\db\Query())
//    ->select(['customer_person_id as id', "CONCAT(name, ' (',email,')') as name"])
//    ->from('table')
//    ->where(['customer_person_id' => $customer_persons_ids])
//    ->all();
 
    /*
    $codebase_items_data = (new \yii\db\Query())
    ->select(['codebase_id as id', "CONCAT(file_path_uri,'/',file_name) as name"])
    ->from('metadata__codebase')
    //->where(['codebase_id' => 1])
    ->all();  
    
var_dump($codebase_items_data);
     * 
     */
    ?>
  
    
    <?php 
    $gridColumn = [
        ['class' => 'yii\grid\SerialColumn'],
        'table_name',
        'has_named_primary_key',
        'has_v3_fields',
        'has_representing_field'
        //['attribute' => 'lock', 'visible' => false],
//        [
//            'class' => 'yii\grid\ActionColumn',
//            'template' => '{save-as-new} {view} {update} {delete}',
//            'buttons' => [
//                'save-as-new' => function ($url) {
//                    return Html::a('<span class="glyphicon glyphicon-copy"></span>', $url, ['title' => 'Save As New']);
//                },
//            ],
//        ],
    ]; 
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => $gridColumn,
        //'pjax' => true,
        //'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-metadata-codebase']],
//        'panel' => [
//            //'type' => GridView::TYPE_PRIMARY,
//            'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
//        ],
        //'export' => false,
        // your toolbar can include the additional full export menu
//        'toolbar' => [
//            '{export}',
//            ExportMenu::widget([
//                'dataProvider' => $dataProvider,
//                'columns' => $gridColumn,
//                'target' => ExportMenu::TARGET_BLANK,
//                'fontAwesome' => true,
//                'dropdownOptions' => [
//                    'label' => 'Full',
//                    'class' => 'btn btn-default',
//                    'itemsBefore' => [
//                        '<li class="dropdown-header">Export All Data</li>',
//                    ],
//                ],
//                'exportConfig' => [
//                    ExportMenu::FORMAT_PDF => false
//                ]
//            ]) ,
//        ],
    ]);
       ?>
     

</div>

yii2-app-basic/views/metadata-dashboard/saveAsNew.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\MetadataCodebase */

$this->title = 'Save As New Metadata Codebase: '. ' ' . $model->codebase_id;
$this->params['breadcrumbs'][] = ['label' => 'Metadata Codebases', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->codebase_id, 'url' => ['view', 'id' => $model->codebase_id]];
$this->params['breadcrumbs'][] = 'Save As New';
?>
<div class="metadata-codebase-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
    'model' => $model,
    ]) ?>

</div>